version: '3'
services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile
        image: php:8.1
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
            - ./dockerfiles/nginx/certs:/etc/nginx/certs
        networks:
            - app-network

    db:
        image: postgres:15
        volumes:
            - ./dockerfiles/postgresql:/etc/postgresql
            - ./postgres-data:/var/lib/postgresql/data
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: postgres
            POSTGRES_PASSWORD: qWwJBTmpH9Ga
            POSTGRES_DB: orchestrator_db
            POSTGRES_USER: orchestrator_user
        networks:
            - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge
